#include "utility/assert_log.h"
#include "utility/collision.h"
#include "utility/recursion_usable_mutex.h"
#include "utility/scoped_mutex.h"
#include "utility/string_utility.h"
#include "utility/user_pointer.hpp"
#include "utility/utf8.h"
#include "utility/write_file_on_destroyed.h"